### ISSUE TITLE
Mod does not display Russian letters

### ISSUE THREAD

**Issue by Tllya** [xen-42/outer-wilds-achievement-tracker#1]
For example:
![unknown (1)](https://user-images.githubusercontent.com/94857119/165484864-2bfbe16e-f95c-4874-9ae9-057e12e49f80.png)
![unknown](https://user-images.githubusercontent.com/94857119/165484859-ac24306a-9ef4-4fc1-b488-452133dfac25.png)

**Comment by xen-42** [comment]
Fixed in https://github.com/xen-42/outer-wilds-achievement-tracker/commit/c2b045885c69da12da06c295c537b2910863751b

**Comment by Tllya** [comment]
Still doesn't display Russian letters in menu
![Безымянный](https://user-images.githubusercontent.com/94857119/165675770-b73bf3a1-fbfe-4b6d-ad86-c13226bbf3bb.png)
![Безымянны2й](https://user-images.githubusercontent.com/94857119/165675773-208ef680-45a8-40f9-beab-f226a37583f9.png)

**Comment by Tllya** [comment]
So reopen pls
